### PR TITLE
changed default limit from 500 to 100 (fixes #18)

### LINKED ISSUE #18: 400 Client Error: BAD REQUEST for url on agents endpoint
The Zopim integration is returning a Bad Request error on the agents endpoint, full log:

> 2019-02-2 14:00:01,159Z    tap - INFO HTTP request to "agents" endpoint took 5.478s, returned status code 400
2019-02-26 14:00:01,159Z    tap - CRITICAL 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/agents?limit=500&since_id=0
2019-02-26 14:00:01,159Z    tap - Traceback (most recent call last):
2019-02-26 14:00:01,159Z    tap -   File "tap-env/bin/tap-zendesk-chat", line 10, in <module>
2019-02-26 14:00:01,160Z    tap -     sys.exit(main())
2019-02-26 14:00:01,160Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 112, in main
2019-02-26 14:00:01,160Z    tap -     raise exc
2019-02-26 14:00:01,160Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 109, in main
2019-02-26 14:00:01,160Z    tap -     main_impl()
2019-02-26 14:00:01,160Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 105, in main_impl
2019-02-26 14:00:01,160Z    tap -     sync(ctx)
2019-02-26 14:00:01,161Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 91, in sync
2019-02-26 14:00:01,161Z    tap -     stream.sync(ctx)
2019-02-26 14:00:01,161Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/streams.py", line 59, in sync
2019-02-26 14:00:01,161Z    tap -     page = ctx.client.request(self.tap_stream_id, params)
2019-02-26 14:00:01,161Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-02-26 14:00:01,161Z    tap -     ret = target(*args, **kwargs)
2019-02-26 14:00:01,161Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/http.py", line 34, in request
2019-02-26 14:00:01,162Z    tap -     response.raise_for_status()
2019-02-26 14:00:01,162Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
2019-02-26 14:00:01,162Z    tap -     raise HTTPError(http_error_msg, response=self)
2019-02-26 14:00:01,162Z    tap - requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/agents?limit=500&since_id=0
2019-02-26 14:00:01,194Z   main - INFO State update: adding bookmarks.agents.offset.id = null
2019-02-26 14:00:01,194Z   main - INFO State update: adding bookmarks.chats.chat.end_timestamp = "2019-02-25T20:43:56Z"
2019-02-26 14:00:01,194Z   main - INFO State update: adding bookmarks.chats.offline_msg.timestamp = "2018-07-20T15:59:15Z"
2019-02-26 14:00:01,194Z   main - INFO State update: adding bookmarks.chats.offset.chat.next_url = null
2019-02-26 14:00:01,194Z target - INFO Exiting normally
2019-02-26 14:00:01,194Z   main - INFO State update: adding bookmarks.chats.offset.offline_msg.next_url = null
2019-02-26 14:00:01,195Z   main - INFO State update: adding currently_syncing = "agents"
2019-02-26 14:00:01,300Z   main - INFO Target exited normally with status 0
2019-02-26 14:00:01,303Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/agents?limit=500&since_id=0". Target succeeded.

>

### PR DESCRIPTION
**Pull request by RinkeRaven**
Limit 500 results in 400 Bad Request Error

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @RinkeRaven, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @RinkeRaven!

Thank you for signing the Singer Contribution License Agreement.

**Comment by KAllan357** [comment]
:+1:

**Comment by KAllan357** [comment]
Released in 0.1.17.

**Review by luandy64 — APPROVED** [review]

**Pull request merged**
